### ISSUE TITLE
since PR #580 building on Windows fails

### ISSUE THREAD

**Issue by sebgod** [ggreer/the_silver_searcher#587]
due to missing `lstat` on Windows,
building fails (change introduced on master in #580)
```
make -f Makefile.w32
gcc -c -O2 -Isrc/win32 -DPACKAGE_VERSION=\"0.28.0\" -Isrc src/main.c -o src/main.o
gcc -c -O2 -Isrc/win32 -DPACKAGE_VERSION=\"0.28.0\" -Isrc src/options.c -o src/options.o
gcc -c -O2 -Isrc/win32 -DPACKAGE_VERSION=\"0.28.0\" -Isrc src/search.c -o src/search.o
gcc -o ag.exe src/decompress.o src/ignore.o src/lang.o src/log.o src/main.o src/options.o src/print.o src/scandir.o src/search.o src/util.o -lz -lpthread -lpcre -llzma -lshlwapi
src/main.o:main.c:(.text.startup+0x38c): undefined reference to `lstat'
src/search.o:search.c:(.text+0xe90): undefined reference to `lstat'
collect2.exe: error: ld returned 1 exit status
make: *** [ag.exe] Error 1
```

**Comment by ggreer** [comment]
Should be fixed now. Sorry about that.

**Comment by sebgod** [comment]
@ggreer , no problem, glad I can help at least with testing.
I'm not yet familiar with the code base to do some development on my own.

Just I noticed there is a another call to ```lstat``` in main.c:164:
```C
            if (opts.one_dev && lstat(paths[i], &s) == -1) {
                log_err("Failed to get device information for path %s. Skipping...", paths[i]);
            }
```
In order to compile the project I added `#ifndef _WIN32   #endif` around that `if`

**Comment by ggreer** [comment]
D'oh. Ok, fixed for realsies this time. One of these days I'll get around to using windows.
