### ISSUE TITLE
Cygwin build fails: off64_t not defined

### ISSUE THREAD

**Issue by aswild** [ggreer/the_silver_searcher#1126]
Regression from #1106: Cygwin defines `_off64_t` but not `off64_t`

```
  CC       src/zfile.o
src/zfile.c:328:27: error: unknown type name ‘off64_t’
 zfile_seek(void *cookie_, off64_t *offset_, int whence) {
                           ^
src/zfile.c:36:31: warning: ‘zfile_seek’ used but never defined
 static cookie_seek_function_t zfile_seek;
                               ^
make: *** [Makefile:483: src/zfile.o] Error 1
```
